services:
  ctf:
    container_name: phoenixctf
    image: phoenixctf:latest
    hostname: phoenixctf
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CUID: "${CUID}"
        CGID: "${CGID}"
        SUID: "${SUID}"
        SGID: "${SGID}"
        PARALLEL_BUILDS: "${PARALLEL_BUILDS}"
      tags:
        - ghcr.io/bruand81/phoenixctf:latest
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    privileged: true
